packages:
  - 'agents'
  - 'plugins/*'
  - 'examples'

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@livekit/*'

catalog:
  '@livekit/rtc-node': ^0.13.25
  ws: ^8.18.0
  '@types/ws': ^8.5.10
