blank_issues_enabled: false
contact_links:
  - name: Slack community chat
    url: https://livekit.io/join-slack
    about: Ask questions and discuss with other LiveKit users in real time
  - name: LiveKit Agents for Python
    url: https://github.com/livekit/agents
    about: The canonical version of LiveKit Agents. Direct feature requests here
